import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { FloatingBasket } from "./components/FloatingBasket";
import { DataProvider } from "./components/providers/DataProvider";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <DataProvider>
            <Header />
            <div className="relative">{children}</div>
            <FloatingBasket />
            <Footer />
          </DataProvider>
        </UserProvider>
      </body>
    </html>
  );
}
