export const navItem = [
  { text: "НҮҮР", path: "/" },
  { text: "ХООЛНЫ ЦЭС", path: "/Menu" },
];
export const foodList = [
  {
    category: "1-Р ХООЛ",
    foodName: "Хуйцай",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Банштай ногоотой шөл",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Банштай хар шөл",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Гурилтай шөл",
    foodPrice: 9500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Жигнэсэн гурилтай шөл",
    foodPrice: 9500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Банштай цай",
    foodPrice: 9500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "1-Р ХООЛ",
    foodName: "Бантан",
    foodPrice: 9500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Гахайн мах",
    foodPrice: 14500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Тахианы мах",
    foodPrice: 14500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Гуляш",
    foodPrice: 11000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Нарийн махан хуурга",
    foodPrice: 11000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Өндөгтэй хуурга",
    foodPrice: 11000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Соустай бөөрөнхий мах",
    foodPrice: 11000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Бүрмэл шницель",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Цуйван",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Өндөгтэй бифштекс",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Сыртэй бифштекс",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Тефтель",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Өндөгтэй бифштекс",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Төмсний хучмал",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Будаатай хуурга",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Шарсан зайдас",
    foodPrice: 10000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Соустай будаа",
    foodPrice: 5000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Хачиртай хуушуур 5ш",
    foodPrice: 11500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "2-Р ХООЛ",
    foodName: "Хачиртай хуушуур 3ш",
    foodPrice: 8500,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "САЛАТ",
    foodName: "Өндөгний салат",
    foodPrice: 6000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "САЛАТ",
    foodName: "Нийслэл салат",
    foodPrice: 5000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "САЛАТ",
    foodName: "Байцааны салат",
    foodPrice: 4000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "САЛАТ",
    foodName: "Луувангийн салат",
    foodPrice: 4000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Хуушуур",
    foodPrice: 2000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Мантуун бууз",
    foodPrice: 2000,
    foodImg:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6IDembxcB_dTL7bvAHs3pyqJQ66cE__gj1g&s",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Жигнэсэн ороомог",
    foodPrice: 2000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Шарсан ороомог",
    foodPrice: 2200,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Шарсан өндөг",
    foodPrice: 1000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Чанасан өндөг",
    foodPrice: 1000,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Бин",
    foodPrice: 700,
    foodImg: "/chicken.webp",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
  {
    category: "ШИРХЭГИЙН ХООЛ",
    foodName: "Мантуу",
    foodPrice: 700,
    foodImg:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFnYghJjK4Jawb8jrRhwJiyRKYGJCpQVD-Ow&s",
    portion: false,
    foodIngredient: "Мах, гурил, давс",
  },
];
export const phoneNumber = ["88657751", "94627751"];
export const categories = [
  { text: "Бүгд", value: "" },
  { text: "1-р хоол", value: "1-Р ХООЛ" },
  { text: "2-р хоол", value: "2-Р ХООЛ" },
  { text: "Салат", value: "САЛАТ" },
  { text: "Ширхэгийн хоол", value: "ШИРХЭГИЙН ХООЛ" },
];
