export const navItem = [
  { text: "НҮҮР", path: "/" },
  { text: "ХООЛНЫ ЦЭС", path: "/Menu" },
];
export const foodList = [
  {
    category: "1-р хоол",
    name: "Хуйцай",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Банштай ногоотой шөл",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Банштай хар шөл",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Гурилтай шөл",
    price: 9500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Жигнэсэн гурилтай шөл",
    price: 9500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Банштай цай",
    price: 9500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "1-р хоол",
    name: "Бантан",
    price: 9500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Гахайн мах",
    price: 14500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Тахианы мах",
    price: 14500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Гуляш",
    price: 11000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Нарийн махан хуурга",
    price: 11000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Өндөгтэй хуурга",
    price: 11000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Соустай бөөрөнхий мах",
    price: 11000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Бүрмэл шницель",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Цуйван",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Өндөгтэй бифштекс",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Сыртэй бифштекс",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Тефтель",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Өндөгтэй бифштекс",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Төмсний хучмал",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Будаатай хуурга",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Шарсан зайдас",
    price: 10000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Соустай будаа",
    price: 5000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Хачиртай хуушуур 5ш",
    price: 11500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "2-р хоол",
    name: "Хачиртай хуушуур 3ш",
    price: 8500,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Салат",
    name: "Өндөгний салат",
    price: 6000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Салат",
    name: "Нийслэл салат",
    price: 5000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Салат",
    name: "Байцааны салат",
    price: 4000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Салат",
    name: "Луувангийн салат",
    price: 4000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Хуушуур",
    price: 2000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Мантуун бууз",
    price: 2000,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6IDembxcB_dTL7bvAHs3pyqJQ66cE__gj1g&s",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Жигнэсэн ороомог",
    price: 2000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Шарсан ороомог",
    price: 2200,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Шарсан өндөг",
    price: 1000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Чанасан өндөг",
    price: 1000,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Бин",
    price: 700,
    image: "/bg.png",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
  {
    category: "Ширхэгийн хоол",
    name: "Мантуу",
    price: 700,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFnYghJjK4Jawb8jrRhwJiyRKYGJCpQVD-Ow&s",
    portion: false,
    ingredient: "Мах, гурил, давс",
  },
];
export const phoneNumber = ["88657751", "94627751"];
